name: sahara_homepage
description: "A new Flutter project."
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  android_intent_plus: ^5.3.0

  font_awesome_flutter: ^10.8.0
  lottie:
  provider: ^6.1.5  #for notification
  carousel_slider:
  animated_text_kit: ^4.2.2
  firebase_auth: ^5.4.1
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  firebase_storage: ^12.4.1
  image_picker: ^1.1.2
  flutter_gif:
  google_sign_in:
  geolocator: ^10.1.0 #for current location
  geocoding: ^2.1.0
  google_maps_flutter: ^2.5.0
  youtube_player_flutter:
  firebase_core:
  cloud_firestore:
  googleapis_auth: ^1.4.0
 # http: ^0.13.6
  #flutter_google_places: ^0.3.0
  #google_api_headers: ^1.4.0
  http: ^1.3.0  # For API calls
  google_mlkit_translation:
flutter_localizations:

  intl: latest_version

dev_dependencies:
  flutter_test:
    sdk: flutter
# rules and activating additional ones.
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/
    #- assets/charitymate-bc611-firebase-adminsdk-fbsvc-8d75db682f.json
    - assets/images/
    - assets/images/WhatsApp Image 2025-04-04 at 3.59.40 PM.jpeg
    - assets/images/WhatsApp Image 2025-04-04 at 4.00.36 PM.jpeg
    - assets/images/WhatsApp Image 2025-04-04 at 4.02.45 PM.jpeg
  #   - images/a_dot_ham.jpeg
